# Generated by Django 4.1.1 on 2022-09-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meetingRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('siteName', models.CharField(max_length=30)),
                ('FloorName', models.IntegerField(verbose_name=[])),
                ('MrNameAndNo', models.CharField(max_length=100)),
                ('furnitureImg', models.ImageField(upload_to='images/')),
                ('ceilingImg', models.ImageField(upload_to='images/')),
                ('ceilingMatTyp', models.CharField(max_length=50)),
                ('CeilingHeight', models.CharField(max_length=50)),
                ('distanceFromAdjancent', models.CharField(max_length=50)),
            ],
        ),
    ]
