# Generated by Django 4.1.1 on 2022-09-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='FloorName',
            field=models.IntegerField(),
        ),
    ]
