# Generated by Django 4.1.1 on 2022-09-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0002_alter_meetingroom_floorname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetingroom',
            old_name='FloorName',
            new_name='floorNo',
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='ceilingImg',
            field=models.ImageField(upload_to='ceiling_images/'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='furnitureImg',
            field=models.ImageField(upload_to='furniture_images/'),
        ),
    ]
