# Generated by Django 4.1.1 on 2022-09-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0003_rename_floorname_meetingroom_floorno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='ceilingImg',
        ),
        migrations.RemoveField(
            model_name='meetingroom',
            name='furnitureImg',
        ),
    ]
