# Generated by Django 4.1.1 on 2022-09-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0004_remove_meetingroom_ceilingimg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetingroom',
            name='floorNo',
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='ceilingImg',
            field=models.ImageField(blank=True, null=True, upload_to='ceiling_images/'),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='furnitureImg',
            field=models.ImageField(blank=True, null=True, upload_to='furniture_images/'),
        ),
    ]
