# Generated by Django 3.2 on 2022-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0005_remove_meetingroom_floorno_meetingroom_ceilingimg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='floorNo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='hangDist',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='lenofPenLight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='meetingroom',
            name='radius',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='CeilingHeight',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='MrNameAndNo',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='ceilingMatTyp',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='distanceFromAdjancent',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='siteName',
            field=models.CharField(default='', max_length=30),
        ),
    ]
