# Generated by Django 3.2 on 2022-09-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0006_auto_20220926_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='ceilingImg',
            field=models.ImageField(default='', upload_to='ceiling_images/'),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='furnitureImg',
            field=models.ImageField(default='', upload_to='furniture_images/'),
        ),
    ]
