# Generated by Django 3.2 on 2022-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0007_auto_20220926_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingroom',
            name='hangDist',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='lenofPenLight',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='meetingroom',
            name='radius',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
