# Generated by Django 3.2 on 2022-09-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteSurveyBackend', '0008_auto_20220926_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='roomDim',
            field=models.CharField(default='', max_length=50),
        ),
    ]
